language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - eggs
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
before_install:
  - pip install --upgrade pip setuptools zc.buildout
  - if [ $PLONE_VERSION == 5.0 ]; then pip install --upgrade setuptools==33.1.1; fi
  - if [ $PLONE_VERSION == 5.1 ]; then pip install --upgrade setuptools==33.1.1; fi
install:
  - sed -ie "s#test-5.0#test-$PLONE_VERSION#" buildout.cfg
  - buildout annotate -c buildout.cfg
  - buildout -c buildout.cfg
script:
  - bin/coverage run bin/test
after_success:
  - bin/coveralls

notifications:
  email:
    - info@redomino.com
